(require 'package)

(defvar marmalade '("marmalade" . "http://marmalade-repo.org/packages/"))
(defvar gnu '("gnu" . "http://elpa.gnu.org/packages/"))
(defvar melpa '("melpa" . "http://melpa.milkbox.net/packages/"))

;; Add marmalade to package repos
(add-to-list 'package-archives marmalade)
(add-to-list 'package-archives melpa t)

(defun packages-install (&rest packages)
  (mapc (lambda (package)
          (let ((name (car package))
                (repo (cdr package)))
            (when (not (package-installed-p name))
              (let ((package-archives (list repo)))
                (package-initialize)
                (package-install name)))))
        packages)
  (package-initialize)
  (delete-other-windows))

;; Install missing packages
(defun init--install-packages ()
  (packages-install
   (cons 'helm melpa)
   (cons 'helm-projectile melpa)
   (cons 'projectile melpa)
   (cons 'paredit marmalade)
   (cons 'slime melpa)
   (cons 'yasnippet melpa)
   (cons 'rainbow-mode melpa)
   (cons 'zencoding-mode marmalade)
   (cons 'js2-mode melpa)
   (cons 'buster-snippets melpa)
   (cons 'clojure-mode melpa)
   (cons 'clojurescript-mode melpa)
   (cons 'clojure-test-mode melpa)
   (cons 'nrepl melpa)
   (cons 'golden-ratio melpa)
   (cons 'expand-region melpa)
   (cons 'mark-multiple melpa)
   (cons 'diminish melpa)
   (cons 'twittering-mode melpa)))

(provide 'package-defuns)
